- siibra/config.py
- test/test_config.py
default/fallback is siibra-{__version__} per HEAD
env key is `SIIBRA_CONFIG_GITLAB_PROJECT_TAG` 
This should improve dev workflow. When developing against a specific ref, instead of explicitly update the ref in file, one can just define the env var
> feat: allow gitlab ref to be defined by env

- examples/BigBrain.ipynb
- examples/Probabilistic_assignment.ipynb
- examples/Walkthrough.ipynb
- siibra/atlas.py
- siibra/ebrains.py
- siibra/features/connectivity.py
- siibra/features/extractor.py
- siibra/features/feature.py
- siibra/features/genes.py
- siibra/features/receptors.py
- siibra/region.py
- siibra/retrieval.py
- test/test_atlas.py
- test/test_extract_transmitter_receptor_densities.py
RegionFeatures now require a concrete Region object at construction time, not only any region specification like an possibly incomplete region name. As a consequence, FeatureExtractors take an atlas object now in their constructor. This moves  region decoding to the Feature Extraction stage for example for ConnectivityProfile features, make the extraction a bit slower, but downstream feature queries safer.
> Enforce region decoding on feature extraction

- siibra/volume_src.py
volume source contain `detail` keys, most are crucial for siibra-explorer to parse the volume source properly (e.g. for ng precomputed source, transform, for auxilliary meshes, metadata such as name "cortex" vs "sulci", and label indexes)
current implementation of siibra-python do not include these metadata.
> feat: add detail to volume src.

- examples/Different species.ipynb
- siibra/__init__.py
- siibra/atlas.py
- siibra/commons.py
- siibra/config.py
- siibra/neuroglancer.py
- siibra/parcellation.py
- siibra/region.py
- siibra/space.py
- siibra/volume_src.py
- test/test_region.py
- test/test_space.py
This version now interprets the new volumeSrc fields in the configurations files properly, and is able to generate Waxholm and Allen Mouse atlases and display their maps, as demonstrated in the new example notebook "Different species.ipynb".
Generated version tag 0.1.a1 with a matched tag in the configurations repo.
Unit tests fixed.
Further work required to add feature queries etc. for rodent and mouse atlases, but it would make sense to merge this to develop already.
> Feature use volume src

- siibra/config.py
configuration currently hosted on `https://jugit.fz-juelich.de` are frequently offline
This PR introduces possible mirrors in the event that the main repo is offline.
[TODO] add hooks to ensure mirrors are up to date to the main repo.
> feat: configure mirror to configuration repos

- siibra/commons.py
- siibra/ebrains.py
- siibra/features/ebrainsquery.py
- siibra/parcellation.py
- siibra/region.py
- siibra/space.py
- test/test_atlas.py
This PR adds the ability for siibra-python to parse, fetch and make available metadata related to spaces, parcellation and regions. (e.g. id added per https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/11/diffs?commit_id=7aa9a29a445f0d8678c47a562f2dcea124367bae )
For now, there exist two types of `origin_datainfo`, simple or ebrains. 
- simple datainfo -> name, property, urls attribute are parsed as json
- ebrains datainfo -> kgId is parsed, and the above information is fetched from KG.
> feat: add origin data info

- siibra/features/connectivity.py
- test/features/test_connectivity.py
This PR fixes an issue discovered by https://github.com/FZJ-INM1-BDA/siibra-python/pull/64#issuecomment-872186814
Up until this point, the parsing of connectivity feature is faulty:
- unparsable region names are discarded
- corresponding profile entry is not trimmed
- during parsing, regionnames and profile are zipped via list comprehension, which results in misalign of profile value -> region
This one of the reasons for the IndexError https://github.com/FZJ-INM1-BDA/siibra-python/blob/8d0a632/test/features/test_connectivity.py#L38 and https://github.com/FZJ-INM1-BDA/siibra-python/blob/8d0a632/test/features/test_connectivity.py#L43
This PR is... potentially less backwards compatible. column_names is no longer a list, but a dictionary, with int as keys. ConnectivityProfile __str__ has an …
> bugfix: error parsing of conn profile

- siibra/config.py
This PR implements basic caching of configurations. The cache is sensitive to the gitlab config site and project tag. Cached files are written to default CACHEDIR defined in the retrieval module.
> Local caching of siibra configurations

- siibra/core/datasets.py
- siibra/core/parcellation.py
- siibra/features/connectivity.py
- siibra/features/ieeg.py
- siibra/features/receptors.py
- siibra/features/voi.py
feat: add version to parcellation model
feat: add/fix type to all feature models
> feat: extend models

- siibra/volumes/parcellationmap.py
Some lambda functions for the cached maploaders of ContinuousParcellationMap were missing default argument definitions, which lead to an error when applying fetch_iter() on probability maps. This PR should fix that problem.
> fix lambda functions of continuous maps

- siibra/volumes/gifti.py
- siibra/volumes/neuroglancer.py
- siibra/volumes/parcellationmap.py
- Thickness of meshes can now be found using a map instance.
- The whole brain can be fetched (default behavior now) from Neuroglancer meshes
- Includes some cleaning in neuroglancer.py
(Sample code is available in rocketchat)
> Refactor v0.4 layer thickness

- siibra/volumes/parcellationmap.py
Example code:
```python
import siibra
import numpy as np
from nilearn import plotting
m = siibra.get_map(parcellation="v2.9", space="MNI colin 27")
spec = m.regions[np.random.randint(0, len(m.regions) - 1)]
print(spec)
region_cmap = m.get_colormap(spec)
mesh = m.fetch(region=spec, format="mesh")
plotting.view_surf((mesh["verts"], mesh["faces"]), cmap=region_cmap )
```
> Added an optional param to get_colormap to get the colormap of a single region

- siibra/retrieval/requests.py
Using a temporary cache file until caching is completed and renaming the file to the actual cache file.
> Bug fix to keyboard interruption during caching

- siibra/core/region.py
- siibra/volumes/parcellationmap.py
- siibra/volumes/sparsemap.py
- test/volumes/test_parcellationmap.py
on discussion with @AhmetNSimsek 
parcellationmap.fetch and sparsemap.fetch had slightly different calling signatures. This PR fixes this, and unifies the call sigs. 
Also the fetch method has been slightly modified to allow str, Region (-> region) or mapindex (-> mapindex) to be supplied as positional argument. 
keywords argument remains functional.
e.g.
```python
index = MapIndex(0, 0)
region_str = "v2 left"
region = Region(*arg, **kwarg)
parcellationmap.fetch(region) 
parcellationmap.fetch(index) 
parcellationmap.fetch(region_str) 
parcellationmap.fetch(region=region) 
parcellationmap.fetch(region=region_str) 
parcellationmap.fetch(index=index)
```
> chore: unify parcellationmap.fetch and sparsemap.fetch

- siibra/commons.py
- siibra/features/anchor.py
- test/features/test_anchor.py
currently, anchor.regions can have `List[Region]` or `Dict[Region, AssignmentQualification]` types.
this ambiguity can lend itself to errors in the future. 
This PR unifies the return type, and always returns `Dict[Region, AssignmentQualification]` type
> chore: clarified+unified anchor.regions types

- examples/03_data_features/000_matchings.py
Newly added voi features increase the doc generation time significantly. Removing voi-feature example from 03-000 to as a temporary fix to be able to produce docs.
> Temp fix to autodoc generation timeout problem

- siibra/configuration/factory.py
While the paradigm data is stored in the preconfigs, it was being replaced with the string "Resting State". The paradigm provides important information when it is provided, so this PR allows siibra to take it from the jsons.
> Get connectivity features' resting-state paradigm from configs

- e2e/volumes/test_parcellationmap.py
- siibra/configuration/factory.py
- siibra/volumes/volume.py
Some critical metadata (e.g. description of pmap of juelich brain regions) are currently been associated with volume (e.g. https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/master/maps/colin27-jba29-continuous.json#L11-14) 
Currently, ebrains property on `Volume` is not utilized (only classes subclassing `Atlasconcept` correctly interprets dataset. since `Volume` does not, it does not properly interprets dataset)
This PR fixes this issue, and volume will now properly have dataset property.
> feat: add ebrains ds to volumes

- siibra/core/parcellation.py
- test/core/test_parcellation.py
With the inclusion of Julich brain 3.0, the possibility of multiple maps of the same space and type has risen. This commit informs the options if not specified, and gets the specified map.
> Allow specifying a map candidate of the same kind

- requirements-test.txt
- requirements.txt
- setup.py
- siibra/retrieval/repositories.py
- siibra/retrieval/requests.py
- test/retrieval/test_requests.py
especially when multiple processes of siibra-python (e.g. in siibra-api) sharing the same cache, sometimes multiple writes can occur, and cause errors.
> fix: file lock in lazy request

- siibra/retrieval/requests.py
- test/features/test_receptors.py
Code to reproduce:
```python
import siibra
malformed_data = []
profiles = siibra.features.molecular.ReceptorDensityProfile.get_instances()
for i, f in enumerate(profiles):
try:
assert len(f.data.columns) == 1 and len(f.data.index) == 101
except:
malformed_data.append(f.)
print(f"Malformed feature: {i} - {f}")
print(malformed_data)
```
This commit removes a row at the decoder level if all the columns are NA.
> Fixes malformation of receptor density profiles due to trailing white spaces

- e2e/features/external/test_ebrains.py
- siibra/features/anchor.py
currently, some (region aliases) anchor.regions.values() are not of the type AnatomicalQualitifcation. This PR fixes this issue.
> fix: anchor.regions.values must be anatQuant

- siibra/volumes/parcellationmap.py
Particularly if one wants to fetch higher-resolution volumes.
> `Map.colorize` should take kwargs to allow fetching with further specification

- siibra/configuration/factory.py
- siibra/features/feature.py
- siibra/volumes/parcellationmap.py
- test/features/test_feature.py
> Add docstring to livequery

- siibra/core/region.py
- test/core/test_region.py
> Do not raise a ValueError when comparing a Region to an unknown object type

- siibra/volumes/parcellationmap.py
As of a6fdbc752286e073e8cc30511c94e214ce58a6b1
The user is not expected to know the `MapIndex` of a region, so `get_region` is used in tandem with `get_index`. Alternatively, one can directly set `label` and/or `volume`. This could be useful when going through a number of volumes/labels in a parcellation map, however, it is not deterministic since some maps are shipped with fragments additionally. So ideally a user should be able to use `get_region` in tandem with `get_index`:
```python
import siibra
mp = siibra.get_map(parcellation="julich 2.9", space="colin 27")
for regionname in mp.regions: 
mp.get_region(
mp.get_index(regionname)
)
```
to obtain region objects. Currently, this code will fail because `index` is not specified within `get_region`.
With this PR, `get_region` raises an …
> When map.get_region takes MapIndex as only argument, it should raise exception

- e2e/volumes/test_parcellationmap.py
- examples/05_anatomical_assignment/001_coordinates.py
- siibra/commons.py
- siibra/volumes/parcellationmap.py
- siibra/volumes/sparsemap.py
Fixes #338
(Also, improves performance)
> Remove overriding assigned point scores

- siibra/volumes/neuroglancer.py
- siibra/volumes/nifti.py
Solves #302
After review, the same should be applied to neuroglancer.
> Preserve map shape and dtype when a map is merged

- config_schema/siibra/map/v0.0.1.json
- siibra/configuration/factory.py
- siibra/retrieval/repositories.py
- siibra/retrieval/requests.py
- siibra/volumes/sparsemap.py
- test/volumes/test_sparsemap.py
This PR introduces:
- Allow a clear definition for a SparseMap from the configuration.
- Legacy method is preserved
-  Allows fetching SparseIndex of a SparseMap from a precomputed SparseIndex in a zip file.
Connected config branch: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/tree/clarifySparsemaps
This decreases the required time it takes to fetch any map from SparseMaps as the SparseIndex is no longer required to be calculated on the fly.
No functionality is removed, so if a SparseMaps does not have stored SparseIndex or the zip file is unreachable, then the Index is calculated as before.
See related issue #334
> Improve sparse map handling

- siibra/__init__.py
- siibra/commons.py
- siibra/volumes/parcellationmap.py
This PR adds an instance table in the form of a data frame for maps (#329). It is strictly additive and does not remove any existing functionality for the other instance tables of class `InstanceTable`.
While more discussion and additions could be had, this is a highly requested feature. Therefore, IMO we should add it as is and continue discussing the remainder under a new issue.
(`InstanceDataframe` could be expanded with similar functionalities of `InstanceTable`, however, for the time bein the goal is to provide an overview. Also, `query` provides a lot of functionalites.)
Usage:
```python
import siibra
print(siibra.maps.head())
print(siibra.maps.columns)
print(siibra.maps.index)
siibra.maps.query("space == 'MNI Colin 27'")
```
> InstanceDataframe for maps (strictly additive, does not remove InstanceTable)

- e2e/volumes/test_parcellationmap.py
- siibra/volumes/parcellationmap.py
During implementation of dataclass for assignments, the 'map value' was forgotten to be assigned for points. Fixes
https://github.com/FZJ-INM1-BDA/siibra-python/issues/338
> Point assignments also have map value

- siibra/retrieval/requests.py
The use of ";" as the default csv decoder delimiter appears to be originally written to parse 1000 brains data. However, now this is resolved in `decoder` section in the corresponding json file. It is inherently not intuitive to use ";" as the default of the csv decoder.
Before merging, the documentation should be checked for any issues with examples or data ingestion in general.
> Detect csv delimiter with Python’s builtin sniffer tool

- siibra/volumes/volume.py
Provides a solution to #318 (and closes #368):
- Fetch the first supported format matching the volume's providers unless the user specifies the volume `format`.
- Try the selected format 6 times and fail.
- On fail, inform the user of the exception, the autoselected format, and other available formats.
Also, adds a lookup dictionary for format shorthand (solves #386)
> If no format is given, only try to fetch single format else fail

- .flake8
- siibra/retrieval/requests.py
Also, includes:
- maintenance of `HttpRequest`
- Flake8 rule exclusion: E731 - do not assign a lambda expression
> Allow automaticly digesting .gz files of gzipped types listed in `DECODERS`

- docs/requirements-doc.txt
- examples/03_data_features/001_receptor_densities.py
- examples/03_data_features/007_comparative_assessment.py
- siibra/commons.py
- siibra/features/connectivity/regional_connectivity.py
- siibra/features/feature.py
- siibra/features/tabular/cortical_profile.py
- siibra/features/tabular/gene_expression.py
- siibra/features/tabular/layerwise_cell_density.py
- siibra/features/tabular/receptor_density_fingerprint.py
- siibra/features/tabular/regional_timeseries_activity.py
- siibra/features/tabular/tabular.py
Note that pandas can use plotly as the backend visualization grammar by pd.options.plotting.backend = "plotly". For simplicity and keeping requirements of siibra-python low, [a prototype implementation](https://github.com/FZJ-INM1-BDA/siibra-python/tree/implementPlotly) has been written.
If plotly is installed in the environment, the plot functions use plotly and return as a plotly.graph_objects.Figure. This object has to_json() method which can be used for siibra-api.
Example: https://siibra-python.readthedocs.io/en/implementplotly/examples/03_data_features/001_receptor_densities.html
> Implement plotly

- siibra/commons.py
Feature categories utilize `InstanceTable` as a class table to simplify querying different modalities that fit into a semantic category. `dataframe` property of  `InstanceTable`s is only useful when there are instances within. Therefore, this will be hidden now for features, that is, `siibra.features.cellular.<TAB>` will not show `dataframe`, nor should it.
> Hide dataframe property from InstanceTables for classes

- e2e/features/activity_timeseries/test_activity_timeseries.py
- e2e/features/connectivity/test_connectivity.py
- examples/03_data_features/006_connectivity_matrices.py
- examples/03_data_features/008_functional_timeseries.py
- siibra/configuration/configuration.py
- siibra/configuration/factory.py
- siibra/features/connectivity/regional_connectivity.py
- siibra/features/feature.py
- siibra/features/tabular/regional_timeseries_activity.py
- siibra/locations/__init__.py
(This PR builds on top of https://github.com/FZJ-INM1-BDA/siibra-python/pull/441)
```python
import siibra
fts = siibra.features.get(siibra.parcellations['julich 2.9'], 'connectivity')
for f in fts:
print(f.name)
print(fts[0][0].data.head())  # 0th subject
print(fts[0].data.head())  # average
```
Also to try:
```python
fts[0][0].plot()
```
```python
fts[0][0].plot(region=fts[0][0].regions[0], backend='plotly')
```
```python
fts[0][0].plot(region=fts[0][0].regions[:20], logscale=True, backend='plotly')
```
TODO:
PS: This will allow the digestion of connectivity features as the other features in siibra-explorer, eliminating the need for handling specially. (caveat: the click and travel mechanism won't work.) (colors should be available from plotly json but not sure it is easy for explorer to …
> Connectivity as compound feature

- siibra/features/feature.py
- Also update parse_featuretype to ignore higher level feature classes (only if they are not requested specifically).
- tidy up feature.match to use list of feature type query when string is provided
> Use dict.fromkeys for removing duplicates  in feature query (for reproducible results order)

- siibra/volumes/parcellationmap.py
```python
import siibra
mp = siibra.get_map('julich 3', 'mni152')
mp.compute_centroids()
```
expected: computes the centroids using the volumes of the map.
actual: cannot fetch the mask
This PR fixes this issue
> Fix: map.compute_centroids fail for maps with no fragments

- siibra/volumes/parcellationmap.py
- test/volumes/test_parcellationmap.py
The following code snippet raised `InsufficientArgumentException` previously. This PR allows fetching such maps when no argument has been provided in `fetch`.
```python
import siibra
mp = siibra.get_map(parcellation='julich 2.9', space='bigbrain')
img = mp.fetch()
```
> Labelled maps with multiple volumes can be fetched wo args as a joint volume

- examples/02_maps_and_templates/007_adding_custom_parcellation.py
- siibra/__init__.py
- siibra/commons.py
- siibra/volumes/__init__.py
- siibra/volumes/parcellationmap.py
This is meant to be a preparation for querying features with volumes. The previous iterations required computation of the relations to the defined maps. With the ability to query with volumes, this computation is unnecessary.
In addition, this PR allows creating a map from multiple volumes and supplying parcellation specifications.
> feat: add maps from nifti and label information

- siibra/explorer/__init__.py
- siibra/explorer/url.py
- siibra/explorer/util.py
allows easy viewer url generation
> feat: add siibra-explorer module

- e2e/features/image/test_image.py
- siibra/core/region.py
- siibra/core/structure.py
- siibra/features/anchor.py
- siibra/features/feature.py
- siibra/volumes/volume.py
```python
import siibra
fts = siibra.features.get(siibra.get_template('mni152').get_boundingbox(), siibra.features.cellular.CellbodyStainedSection)
assert len(fts) == 47
```
But as of [d390948](https://github.com/FZJ-INM1-BDA/siibra-python/commit/d39094856c16a1785dbb9a85ab5dde361eb85a3e) siibra cannot find any.
> Fix image query

- siibra/features/anchor.py
- siibra/features/feature.py
- siibra/features/tabular/bigbrain_intensity_profile.py
- siibra/features/tabular/layerwise_bigbrain_intensities.py
- siibra/livequeries/bigbrain.py
This PR increases the speed of combining anchors of Bigbrain intensity profiles significantly since the pairwise summing of point anchors scales linearly with the number of points. Potentially, there could be 170k points if one queries for the whole big brain template. This could take up to an hour with the current methods. This PR allows the implementation of a method special to such features to quickly produce a merged anchor.
```python
import siibra
fts = siibra.features.get(siibra.get_template('bigbrain'), siibra.features.cellular.BigBrainIntensityProfile)
```
Or simply
```python
import siibra
fts = siibra.features.get(siibra.get_region('julich 2.9', 'occipital cortex'), siibra.features.cellular.BigBrainIntensityProfile)
```
speeds up from 136.9s to 0.03s (on an i5-1145G7)
> Increase intensity profile compounding speed

- siibra/volumes/volume.py
- test/volumes/test_volume.py
During the last refactoring, this method has been changed a few times, leaving some artifacts and small issue to resolve. This PR addresses these.
- Clean up the code
- Repeat only in case of too many requests
- Check if "resolution_mm" supplied without format and set to NG (this behaviour already existent in `parcellationmap.Map.fetch()` but this is going to be removed as it is not it's job.) (Alternatively, the fetch can fail at, say `NiftiProvider.fetch()` but it is not user's job to know which formats are shipped with different resolutions. And since we decided against resampling nifti images if resolution_mm is supplied, this seems to be the best solution at the moment.)
- `formats` property should only list actual formats otherwise recursion occurs.
> Maint: `volume.fetch`

- siibra/retrieval/cache.py
- siibra/retrieval/requests.py
- test/retrieval/test_cache.py
Since warmup writes files, it is potentially possible to have multiple process trying to warmup simultaneously. 
This PR prevents simultaneous write by using a FileLock (or SoftFileLock in windows).
> fix: write lock for warmup

- siibra/commons.py
The `commons.connected_components` always returned at least two components - the background and the actual foreground structure. Of course the background is not desired. This PR excludes it.
I am quite sure that earlier siibra versions did not include the background component.
> Exclude background from connected_components

- e2e/volumes/test_parcellationmap.py
- siibra/volumes/providers/gifti.py
Test snippet:
```python
import siibra
from nilearn import plotting
mp = siibra.get_map('julich 2.9', 'fsaverage')
mesh = mp.fetch('hoc1 left')
plotting.view_surf(
surf_mesh=[mesh['verts'], mesh['faces']],
surf_map=mesh['labels'],
cmap=mp.get_colormap(),
symmetric_cmap=False, colorbar=False
).open_in_browser()
```
> Fix: fetch specific label from gii labels

- siibra/locations/boundingbox.py
- siibra/locations/pointset.py
The pointset - boundingbox on main raised an exception if no points were inside the bonding box.
This PR should fix the problem.
> fix: pointset intersection with boundingbox fails if no points inside

- siibra/features/__init__.py
fix closure bug
see a simplified reproduction:
```python
from concurrent.futures import ThreadPoolExecutor
from functools import partial
def call_fn(fn):
fn()
def main():
arr = []
for i in range(10):
def fn(j):
print(j)
arr.append(
partial(fn, i)
)
with ThreadPoolExecutor(4) as ex:
list(ex.map(
call_fn,
arr
))
def faulty():
arr = []
for i in range(10):
def fn():
print(i)
arr.append(fn)
with ThreadPoolExecutor(4) as ex:
list(ex.map(
call_fn,
arr
))
if __name__ == "__main__":
print("faulty")
faulty()
print("main")
main()
```
prints
```
faulty
9
9
9
9
9
9
9
9
9
9
main
0
1
3
4
5
2
9
7
8
6
```
> fix: python closure is weird

- e2e/volumes/test_parcellationmap.py
- siibra/configuration/configuration.py
- siibra/retrieval/requests.py
- siibra/volumes/providers/__init__.py
- siibra/volumes/providers/freesurfer.py
- siibra/volumes/volume.py
```python
import siibra
from nilearn import plotting
conn = siibra.retrieval.repositories.GithubConnector("FZJ-INM1-BDA", "siibra-configurations", "add_visfAtlas")
siibra.use_configuration(conn)
mp = siibra.get_map(parcellation="visf", space="fsaverage")
mesh = mp.fetch(variant='inflated')
plotting.view_surf([mesh['verts'], mesh['faces']], surf_map=mesh['labels'], cmap=mp.get_colormap(), symmetric_cmap=False).open_in_browser()
```
See https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles for details of the freesurfer .annot files and https://nipy.org/nibabel/reference/nibabel.freesurfer.html#read-annot for implementation detail.
> Read freesurfer .annot files as fsaverage mesh labels

- siibra/core/parcellation.py
```ipython
import siibra
p = siibra.parcellations['julich 3.1']
p.get_region('LP (Thalamus, lateral posterior Nucleus) right')
```
expected:
```python
<Region(identifier='minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-310_LP_THALAMUS_LATERAL_POSTERIOR_NUCLEUS_RIGHT', name='LP (Thalamus, lateral posterior Nucleus) right', species='Homo sapiens')>
```
but it was raising RuntimeError. This PR fixes this issue.
> Fix: get_region(spec) exact match if spec is a region key

- e2e/volumes/test_extracting_bbox_from_template.py
- siibra/volumes/providers/neuroglancer.py
- siibra/volumes/providers/nifti.py
- siibra/volumes/volume.py
> clip voi to template's to if voi lies partially outside of the template

- e2e/features/image/test_image.py
- siibra/locations/boundingbox.py
- siibra/locations/point.py
- siibra/locations/pointset.py
This PR fixes the no intersection issue when the intersection of 2 bounding boxes is planar and hence have volume 0 resulting in None. This meant that while there are some intersections, these were ignored. Also, the edge case, the intersection is just a point, is accounted for.
code to reproduce the issue on [current main](31b091200d7c3f3d041e762925ff6571d862268a)
```python
import siibra
points = siibra.PointSet(
[
[-35.72, -1.87, 35.03],
[-33.7, -1.87, 36.2],
[-32.56, -1.87, 34.34],
[-35.62, -1.87, 35.2],
],
"bigbrain",
)
matched_sections = siibra.features.get(
points, siibra.features.cellular.CellbodyStainedSection
)
assert len(matched_sections) > 0
voi = points.boundingbox
patch_1mu = matched_sections[0].fetch(voi=voi, resolution_mm=-1)
```
> fix bbox planar intersection

- e2e/core/test_space.py
- siibra/volumes/providers/nifti.py
As of 4fd15440a796703128fcb85da2b4e28c6154b8e2, fetching voi from nifti volumes were broken. This PR fixes this issue.
> Fix nifti fetch voi

- .github/workflows/siibra-testing.yml
- siibra/core/parcellation.py
- siibra/exceptions.py
- test/core/test_parcellation.py
Replaces https://github.com/FZJ-INM1-BDA/siibra-python/pull/460
> Raise if `get_map` can't find any maps instead of logging and returning None

- siibra/exceptions.py
- siibra/locations/boundingbox.py
- siibra/locations/pointset.py
- siibra/volumes/parcellationmap.py
- siibra/volumes/volume.py
Fixes https://github.com/FZJ-INM1-BDA/siibra-python/issues/621
> Raise when a `PointSet` is initialized empty

- e2e/features/test_get.py
- siibra/core/region.py
- siibra/livequeries/bigbrain.py
- siibra/locations/boundingbox.py
- siibra/locations/pointcloud.py
> Fix: query BigBrainProfileIntensity with locations

- siibra/volumes/parcellationmap.py
```python
import siibra
from nilearn import plotting
mp = siibra.get_map("deep bundles", "mni152")
cmap = mp.get_colormap(allow_random_colors=True)  # keyword has to be specified
plotting.view_img(mp.fetch(), cmap=cmap, symmetric_cmap=False).open_in_browser()
```
Uses the number of regions to determine the random seed for reproducibility.
> Allow random cmap creation for `map.get_color_map`

- siibra/volumes/providers/neuroglancer.py
When fetching an axis aligned flat volume of interest translating to exactly 1 voxel "thickness" in one dimension, the NeuroglancerScale fetching method rounds up to a 2 voxel array. In my example, fetching in bigbrain space with `Bounding box from (36.58,-0.10,8.33)mm to (38.64,-0.08,11.71)mm in BigBrain microscopic template (histology) space` retrieved an image array of shape (160, 2, 99).
This is critical, since several analysis workflows that I had implemented with siibra rely on the possibility to fetch a 2D patch from properly sized bounding boxes in physical coordinates, and would now confront me to resolve the ambiguity downstream.
The problem is caused by taking `floor`of the minpoint and `ceil` of the max point to compute the target shape as their difference, resulting in a …
> Rounding scheme for neuroglancer fetching needs revision

- examples/tutorials/2025-paper-fig5.py
- siibra/features/image/sections.py
I rewrote the code example to make it closer to the manuscript figure and better understandable:
- except for the initial raw voxel plot, all plots are done in physical coordinates using nilearn.plotting, removing all explicit point to voxel conversions. I achieved this by finding out how we can work with the 2D canvases of nilearn's 3D plot to plot contours, points, bounding boxes
- The region of interest is not any more explicit, but defined just from a bounding box around a probability threshold of the pixels, so more intuitive now.
- complicated filtering and aggregation of layer 4 vertex projections now much simplified. filtering removed since the plotting command filters implicitly.
- overview plot with section position on glass brain now also implemented.
The PR should work, I …
> Revise Figure 5 code example
