FZJ-INM1-BDA/siibra-python

- .github/workflows/python-package.yml
- setup.py
> update python req, added numpy dep

- siibra/parcellation.py
> feat: add modality and version parsing

- siibra/atlas.py
> chore: remove unused check

- siibra/ebrains.py
- siibra/features/__init__.py
- siibra/features/kg_regional_features.py
> feat: allow kg datasets to be fetched

- examples/BigBrain.ipynb
- siibra/atlas.py
- siibra/neuroglancer.py
- siibra/parcellation.py
- siibra/region.py
- siibra/space.py
- siibra/volume_src.py
This feature models the resolution specifications in public methods of the NgVolume class to be given in millimeters in physical space. Voxel specifications and "mip" parameters are only handeld internally in the class to avoid confusion.
> Feature resolutions in mm

- examples/BigBrain ROI access.ipynb
- examples/Probabilistic_assignment.ipynb
- examples/Walkthrough.ipynb
- siibra/atlas.py
- siibra/commons.py
- siibra/features/connectivity.py
- siibra/parcellationmap.py
- siibra/space.py
- siibra/volumesrc.py
- test/test_region.py
see new notebook BigBrain ROI access to a documented example
> Access to volumes of interests for BigBrain and its maps

- examples/Region overlaps.ipynb
- siibra/parcellationmap.py
See example notebook "region overlaps". Simple computation of overlaps of a continuous  region in MNI space against a continuous parcellation map.
> Computation of continuous region overlaps

- siibra/volumesrc.py
volume_type attr of precompmesh was left out. this PR adds the attr back.
> bugfix: add volme type to precompmesh

- siibra/atlas.py
> Chore: Minor fix to atlas select parcellation API

- siibra/atlas.py
- siibra/config.py
- siibra/ebrains.py
- siibra/features/connectivity.py
- siibra/features/ebrainsquery.py
- siibra/features/feature.py
- siibra/parcellation.py
- siibra/region.py
- test/features/test_ebrainsquery.py
supercedes #61
After discussion, this is a simplified, but equally effective:
```sh
--- preheat-1: 242.01770949363708 seconds ---
--- preheat0: 242.37783551216125 seconds ---
--- preheat1: 0.36009788513183594 seconds ---
--- with preheat again: 0.3659327030181885 seconds ---
```
> feat: improve the response time of (ebrains) features

- .github/workflows/siibra-testing.yml
- siibra/features/connectivity.py
- siibra/features/extractor.py
chore: remove verbose debugging during test
> bugfix: do not cache pick selection

- siibra/parcellation.py
- test/test_parcellation.py
fixes how deprecated flag is parsed
> bugfix: fixing deprecated flag parse

- siibra/core/parcellation.py
- test/core/test_parcellation.py
> bugfix: find_regions ranks result

- pytest.ini
- siibra/core/atlas.py
- siibra/core/parcellation.py
- siibra/core/space.py
- siibra/features/connectivity.py
- siibra/features/ebrains.py
- siibra/features/feature.py
- siibra/features/receptors.py
- test/features/test_ebrainsquery.py
> bugfix: filter dataset by species

- siibra/core/atlas.py
- siibra/core/datasets.py
- siibra/core/parcellation.py
- siibra/core/region.py
- siibra/features/feature.py
- siibra/features/receptors.py
- siibra/volumes/volume.py
add additional fields necessary for functioning of siibra-explorer
> feature: addition to pydantic models

- siibra/core/space.py
- siibra/features/receptors.py
- siibra/features/voi.py
- test/core/test_parcellation.py
- extend models for location, bounding box, receptor dataset
> feat: extend models

- siibra/volumes/volume.py
- test/volumes/test_volume.py
(some values on siibra-config is incorrect)
> feat: auto set ng volume map type

- siibra/core/region.py
- siibra/volumes/volume.py
- test/core/test_region.py
- test/features/test_voi.py
bugfix: region model to_model simplification
> bugfix: use xform in json as defacto xform

- siibra/core/datasets.py
- siibra/core/region.py
- siibra/volumes/volume.py
- test/core/test_region.py
- test/volumes/test_volume.py
region label index inconsistency
temporary fix to #185
> tmp fix: jba29 in big brain

- examples/03_data_features/004_gene_expressions.py
- siibra/core/region.py
- siibra/features/feature.py
- siibra/features/query.py
- test/features/test_features.py
re-enable thresholding of continuous maps for spatial features
ping @skoehnen , per our discussion yesterday. Can you take a look at this PR? If everything looks right, can you merge, and fix the corresponding notebook in tutorial repo?
> feat: allow thresholding cont maps for spatialfeat

- siibra/features/connectivity.py
- siibra/retrieval/requests.py
changes required for https://github.com/FZJ-INM1-BDA/siibra-api/issues/100
> Fix connectivity model

- siibra/__init__.py
- siibra/core/region.py
- siibra/retrieval/requests.py
- test/core/test_region.py
chore: added user agent
chore: bumped version
> feat: added region desc if exists

- siibra/__init__.py
- siibra/core/region.py
- test/core/test_region.py
> WIP fix when multiple centroids are available

- siibra/core/datasets.py
- siibra/core/region.py
- siibra/features/ebrains.py
> use preconfigured ebrains info

- siibra/core/serializable_concept.py
- siibra/retrieval/requests.py
bugfix: fix gzip encoding
chore: added terminal feedback when token is fetched
> bugfix: fix gzip encoding

- siibra/retrieval/requests.py
```python
import siibra
siibra.fetch_ebrains_token(enable_flow=True) # or siibra.fetch_ebrains_token(True)
```
> Simplify device flow for notebooks

- siibra/core/region.py
Closes issue #240:
It is sufficient to make `region.find()` support regex syntax to provide it for `parcellation.get_region()`.
Example:
```python
import siibra
import re
julich_brain = siibra.parcellations.get('julich 2.9')
print(julich_brain.find('/hOc[24].*right/iS'))
print(julich_brain.find(re.compile('hOc[24].*right', flags=re.S | re.I)))
```
> regex syntax support for region.find(), i.e.,  '/pattern/flags'

- .github/workflows/siibra-testing.yml
- e2e/features/external/test_ebrains.py
- examples/03_data_features/000_matchings.py
- examples/03_data_features/005_ebrains_datasets.py
- siibra/features/external/__init__.py
- siibra/features/external/ebrains.py
- siibra/livequeries/ebrains.py
- siibra/retrieval/datasets.py
- siibra/retrieval/repositories.py
- siibra/retrieval/requests.py
- test/features/external/test_ebrains.py
- test/features/test_ebrainsquery.py
> feat: cached ebrains queries

- siibra/volumes/parcellationmap.py
- test/volumes/test_parcellationmap.py
chore: make get_index more specific
test: added test to get_index
> [chore] make error in Map.get_index more specific

- e2e/features/test_get.py
- siibra/__init__.py
- siibra/features/feature.py
- siibra/features/image/image.py
- siibra/locations/point.py
bugfix: image should not have configuration_folder
test: add get all features test
chore: add typing
chore: generalize category as class var of Feature
chore: expose cache on siibra
> bugfix: Image should not  have configuration folder + misc fixes

- siibra/configuration/factory.py
- siibra/features/dataset/ebrains.py
- siibra/livequeries/ebrains.py
- siibra/retrieval/__init__.py
- siibra/retrieval/datasets.py
- siibra/retrieval/requests.py
the api will be deprecated in the coming weeks.
The queries should be running through snapshots already.
> chore: remove live query of kg v1

- e2e/features/connectivity/test_connectivity.py
- siibra/features/connectivity/functional_connectivity.py
- siibra/features/feature.py
fix: Feature.match should return unique feature instances
fix: regional connectivity should return unique feature id
fixes https://github.com/FZJ-INM1-BDA/siibra-python/issues/269
> Fix: dedup feature_id and feature instances

- e2e/features/test_get.py
- siibra/features/feature.py
- test/features/test_feature.py
> feat: add feature get instance by id

- siibra/features/dataset/ebrains.py
- siibra/locations/location.py
- siibra/locations/pointset.py
chore: update category of ebrains datafeature
chore: add typing to location methods
> chore: fix category of ebrains datafeature (dataset -> other)

- e2e/core/test_region.py
- examples/01_atlases_and_parcellations/005_brain_region_spatialprops.py
- siibra/core/region.py
> fix: spatial props sort by volume

- e2e/core/test_region.py
- siibra/core/parcellation.py
- siibra/core/region.py
> Clean region.find() and parcellation.get_region() up

- .github/workflows/siibra-testing.yml
- e2e/volumes/test_parcellationmap.py
- siibra/volumes/sparsemap.py
- test/volumes/test_sparsemap.py
test: mod e2e test for sparsemap
feat: add caching to e2e tests
> test: add test to sparsemap_sparse_index

- .github/workflows/siibra-testing.yml
- e2e/volumes/test_parcellationmap.py
- siibra/volumes/sparsemap.py
- test/volumes/test_sparsemap.py
> Use unique name for the cache of sparseindices

- examples/03_data_features/000_matchings.py
Re-adds VolumeOfInterest example.
Closes #155
> add VolumeOfInterest search in example 03_000

- examples/03_data_features/007_comparative_assessment.py
[The created figures was not readable](https://github.com/FZJ-INM1-BDA/siibra-python/issues/376)
> example 03_007 last figure layout fix

- siibra/configuration/factory.py
- siibra/volumes/sparsemap.py
sparsemap.py will receive further updates after reworking the zipfile connector:
- remove the need to download the whole zip file
- return bytes and load to memory (important for api)
> Remove sparseinedx url connection. Simplify factory.build_map

- e2e/volumes/test_parcellationmap.py
- siibra/volumes/parcellationmap.py
```python
import siibra
mp = siibra.maps.COLIN27_JBA29_LABELLED
mp_img = mp.fetch()
print(mp_img.shape)
template = siibra.spaces['colin27'].get_template().fetch()
print(template.shape)
resamp_template = mp.get_resampled_template()
print(resamp_template.shape)
```
Out:
```
(256, 256, 256)
(181, 217, 181)
(256, 256, 256)
```
> Get resampled template of a map instance

- pytest.ini
- siibra/retrieval/requests.py
- test/retrieval/test_retrieval_download_file.py
Enabled retrieval tests.
ZipfileRequest test is updated with different zipfile.
Satisfy Flake8 in requests.py.
> HttpRequest.find_suitable_decoder returns None if no suitable decoder found

- siibra/retrieval/requests.py
fix: some text on getting ebrains tokens
> fix: adhere to oidc spec for scope

- siibra/__init__.py
- siibra/core/__init__.py
- siibra/features/__init__.py
- siibra/volumes/__init__.py
> Add preloading preconfigs of modules to memory

- siibra/core/atlas.py
- siibra/core/concept.py
> Sort atlas concepts by their name (within the same class)

- pytest.ini
- siibra/features/dataset/ebrains.py
- siibra/livequeries/ebrains.py
- siibra/retrieval/datasets.py
- test/features/external/test_ebrains.py
- test/features/test_ebrainsquery.py
EbrainsFeature queries have been using KG v1 connection. This PR makes general adjustments to ebrains data features around EbrainsDatasetVersionV3 queries.
> Migrate ebrainsFeature to EbrainsDatasetVersionV3

- siibra/livequeries/bigbrain.py
- Pull profile data from EBRAINS https://search.kg.ebrains.eu/instances/26d25994-634c-40af-b88f-2a36e8e1d508,
- If a higher level region is queried, choose a joint space while prioritizing BigBrain space
- Pull mesh data from bigbrain ftp, https://ftp.bigbrainproject.org/bigbrain-ftp/BigBrainRelease.2015/3D_Surfaces/Apr7_2016/gii/
EDT:: todos are moved to issues
> Refactor bigbrain livequery to streamline results and data sources

- .github/workflows/coverage.yml
- .github/workflows/dockerimg.yml
- .github/workflows/pyblish-release-to-pypi.yml
- .github/workflows/siibra-testing.yml
- .github/workflows/test-examples.yml
- e2e/features/connectivity/test_connectivity.py
- siibra/features/connectivity/regional_connectivity.py
- siibra/features/dataset/ebrains.py
- siibra/features/feature.py
- siibra/features/image/image.py
- siibra/features/tabular/tabular.py
allow feature to be exported as zip
fixes #440
> feat: add export to feature

- siibra/commons.py
- siibra/features/anchor.py
> fix: correctly use Parcellation.find_regions in anchor

- config_schema/siibra/repository/localfolder/v1.0.0.json
- siibra/configuration/factory.py
Hello @dickscheid and @AhmetNSimsek  -  for my usecase it would make sense to access local data directly with the custom configs. It was surprisingly easy to achieve with exposing the existing `LocalFileRepository`.
What do you think?
> Local repository

- siibra/features/tabular/tabular.py
Fixes https://github.com/FZJ-INM1-BDA/siibra-python/issues/475
> Display yerr label on tabular feature plots

- siibra/retrieval/repositories.py
solves https://github.com/FZJ-INM1-BDA/siibra-python/issues/292
> Fix use of local configurations on windows

- siibra/volumes/parcellationmap.py
#493  did not fully resolve issues with out-of-bounds points when sampling volumes (the fix only worked for integer points). I unified the code branches to handle integers, lists, and numpy arrays using the same code (less error-prone). The bounds check should now work as expected, for all valid input types.
> Fix bounds check when sampling volumes with points

- siibra/commons.py
- siibra/configuration/factory.py
- siibra/core/concept.py
- siibra/features/feature.py
- siibra/retrieval/datasets.py
Also solves https://github.com/FZJ-INM1-BDA/siibra-python/issues/412
> maint: add license, authors, doi_or_url to concepts

- siibra/explorer/__init__.py
- siibra/explorer/url.py
- siibra/explorer/util.py
allows easy viewer url generation
> feat: add siibra-explorer module

- e2e/core/test_region.py
- examples/02_maps_and_templates/004_access_bigbrain.py
- siibra/core/region.py
- siibra/features/image/image.py
- siibra/locations/boundingbox.py
- siibra/volumes/providers/gifti.py
- siibra/volumes/providers/neuroglancer.py
- siibra/volumes/providers/nifti.py
- siibra/volumes/providers/provider.py
- siibra/volumes/volume.py
- test/volumes/test_volume.py
Solves bounding box of region's possibly resulting to be the whole space
> `provider.boundingbox` -> `provider.get_boundingbox()`

- e2e/volumes/test_parcellationmap.py
- siibra/commons.py
- siibra/volumes/parcellationmap.py
- siibra/volumes/sparsemap.py
During refactoring (https://github.com/FZJ-INM1-BDA/siibra-python/pull/480/commits/6fe6fa6f4955342cdd0a76a2076d3594493442b9), image resampling was forgotten to be replaced. This fixes volume assignments to labelled maps.
> Fix assigning uncertain points to labelled maps #526

- siibra/volumes/providers/neuroglancer.py
- test/volumes/providers/test_neuroglancer.py
fixes #530 , specifically https://github.com/FZJ-INM1-BDA/siibra-python/issues/530#issuecomment-1904333095
> fix: info uses siibra.retrieval module for local file cache

- .github/workflows/coverage.yml
(Based on discussions in the link provided in the issue) could potentially solve #261. Should watch out for upload failures afterward.
> Use codecov v3

- siibra/configuration/configuration.py
- siibra/retrieval/repositories.py
- siibra/retrieval/requests.py
> Use Github repo connector for configurations

- e2e/features/molecular/test_genes.py
- siibra/livequeries/allen.py
> fix: allen gene exp query w a list of genes

- siibra/features/__init__.py
- siibra/features/tabular/cortical_profile.py
Naked assertion without error message is really hard to debug for downstream applications. 
This PR adds some assertion messages to check sanity method
> fix: add assertion error message

- siibra/commons.py
- siibra/features/tabular/cell_density_profile.py
- siibra/features/tabular/layerwise_cell_density.py
Fixes https://github.com/FZJ-INM1-BDA/siibra-python/issues/276 and https://github.com/FZJ-INM1-BDA/siibra-python/issues/509
> fix: cell density profile

- e2e/volumes/test_volume.py
- siibra/core/parcellation.py
> Change default of find_topmost in `parcellation.get_region` to False

- siibra/core/region.py
> maint: `region.supported_spaces` and `region.mapped_in_space()`

- siibra/features/anchor.py
The following tests are failing for 0.4EOL (> v1.x pass these tests):
```python
import siibra
r = siibra.get_region('wax', 'Fasciola cinereum')
fts = siibra.features.get(r, 'receptor')
assert len(fts) > 0
assert fts[0].last_match_description == "'Hippocampal region' contains 'Fasciola cinereum'"
ebrains_fts = siibra.features.get(r, 'ebrains')
assert len(ebrains_fts) >= 4  # currently there is 4 but there can be more
```
This PR addresses it.
> v0.4 EOL - match region specs of features to higher level regions
